# Generated by Django 6.0.6 on 2026-07-04 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст секрета')),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Хэш пароля')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Секрет',
                'verbose_name_plural': 'Секреты',
                'ordering': ['-created_at'],
            },
        ),
    ]
